# on off switch
switch:
  pin: 23

# miotion sensors
sensors:
  pins:
    - 24

# bluetooth
bluetooth:
  devices:
    - aa:bb:cc:dd:ee:ff
    - 00:11:22:33:44:55

# horn
horn:
  pin: 25
  duration: 15 # in seconds

# camera
camera:
  device: /dev/video0
  images_dir: /var/watchmen/DCIM
  quality: 75
  resolution: 800x600

# file uploader
uploader:
  ftp:
    ip: 10.10.10.10
    port: 21
    user: ftpuser
    password: ftppass

# notifiers
notifier:
  # smtp config
  mail:
    user: sender@gmail.com
    password: foopass
    host: smtp.gmail.com
    port: 587
    from: sender@gmail.com
    recipients:
      - recipient@gmail.com
      - recipient@gmail.com

# LCD SSD1306 I2C
lcd:
  i2c_buss_addr: 0x01
  dev_addr: 0x3c
  height: 64
  width: 128

